version: "3"

services:
  db:
    image: postgres
    container_name: projeto-extensao-helper
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: prog-web-2024
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5433:5432
    logging:
      driver: json-file
      options:
        max-size: 100m

volumes:
  pgdata:
